import { checkConfigs } from '@/utils';
import { checkPerm } from '@/utils';

export default () => ({
  $configs: checkPerm('*'),
  $account: !0,
  $system: checkPerm('@tenant:query', '@user:query', '@role:query', '@perm:query'),
  $system$tenant: checkConfigs('tenantEnabled') && checkPerm('@tenant:query'),
  $system$user: checkPerm('@user:query'),
  $system$role: checkPerm('@role:query'),
  $system$perm: checkPerm('@perm:query'),
  $tenant$query: checkPerm('@tenant:query'),
  $tenant$create: checkPerm('@tenant:add'),
  $tenant$update: checkPerm('@tenant:update'),
  $tenant$delete: checkPerm('@tenant:delete'),
  $tenant$auth: checkPerm('@tenant:update'),
  $user$query: checkPerm('@user:query'),
  $user$create: checkPerm('@user:add'),
  $user$update: checkPerm('@user:update'),
  $user$delete: checkPerm('@user:delete'),
  $role$query: checkPerm('@role:query'),
  $role$create: checkPerm('@role:add'),
  $role$update: checkPerm('@role:update'),
  $role$delete: checkPerm('@role:delete'),
  $role$auth: checkPerm('@role:update'),
  $perm$query: checkPerm('@perm:query'),
  $perm$create: checkPerm('@perm:add'),
  $perm$update: checkPerm('@perm:update'),
  $perm$delete: checkPerm('@perm:delete'),
});
