import { checkPerm } from '@/utils';

export default ({ perms } = {}) => ({
  $system: checkPerm(perms, '@tenant:query', '@user:query', '@role:query', '@perm:query'),
  $system$tenant: checkPerm(perms, '@tenant:query'),
  $system$user: checkPerm(perms, '@user:query'),
  $system$role: checkPerm(perms, '@role:query'),
  $system$perm: checkPerm(perms, '@perm:query'),
  $tenant$query: checkPerm(perms, '@tenant:query'),
  $tenant$create: checkPerm(perms, '@tenant:add'),
  $tenant$update: checkPerm(perms, '@tenant:update'),
  $tenant$delete: checkPerm(perms, '@tenant:delete'),
  $tenant$auth: checkPerm(perms, '@tenant:update'),
  $user$query: checkPerm(perms, '@user:query'),
  $user$create: checkPerm(perms, '@user:add'),
  $user$update: checkPerm(perms, '@user:update'),
  $user$delete: checkPerm(perms, '@user:delete'),
  $role$query: checkPerm(perms, '@role:query'),
  $role$create: checkPerm(perms, '@role:add'),
  $role$update: checkPerm(perms, '@role:update'),
  $role$delete: checkPerm(perms, '@role:delete'),
  $role$auth: checkPerm(perms, '@role:update'),
  $perm$query: checkPerm(perms, '@perm:query'),
  $perm$create: checkPerm(perms, '@perm:add'),
  $perm$update: checkPerm(perms, '@perm:update'),
  $perm$delete: checkPerm(perms, '@perm:delete'),
});
